### ISSUE TITLE
[BUG] YT無法顯示

### ISSUE THREAD

**Issue by tt1034** [zoosewu/PTTChatOnYoutube#118]
**問題描述**
YOUTUBE 開啟PTT聊天室的P按鈕無法顯示
目前有嘗試重新安裝、關掉AD block都沒有效
另外在圖奇可以正常使用

**相關訊息:**
 - 使用的作業系統:Win10
 - 使用的瀏覽器:Chrome
 - 使用的套件版本:3.0.5
 - 使用的網站網址:YOUTUBE

**Comment by zoosewu** [comment]
![image](https://user-images.githubusercontent.com/75579796/179813638-68eed37f-ba41-4d0e-9b3e-20b9f9921d54.png)
看一下這個選項有沒有打開

**Comment by terry12369** [comment]
有開啟了，Chrome跟Edge的YT都沒辦法看到P

**Comment by aces3732** [comment]
一樣問題，youtube無法顯示P，重新安裝，用暴力猴或tempermonkey都沒有用

**Comment by zoosewu** [comment]
@terry12369 @aces3732 @tt1034 
可以截圖一下YT畫面 嗎
還有打開F12看一下有沒有訊息最右邊是 _Youtube聊天室顯示PTT推文_ 像下面一樣
![image](https://user-images.githubusercontent.com/75579796/180763741-f97a9c02-df19-4acd-a79d-f44602478a1e.png)
然後是**紅底的** 有的畫幫我截圖上來

**Comment by aces3732** [comment]
[image: {929EFDDC-2502-467B-A4C5-04360947DD65}.png]

F12右邊console顯示如下

LegacyDataMixin will be applied to all legacy elements.
Set `_legacyUndefinedCheck: true` on element class to enable.
userscript.html?name=pttchatonyoutube.user.js&id=1a4522e4-1be2-41a6-a51b-7319beb6ae6e:4602
PTTChatOnYT Script started at Youtube, href:
https://www.youtube.com/watch?v=IJwtgGEz2ec
userscript.html?name=pttchatonyoutube.user.js&id=1a4522e4-1be2-41a6-a51b-7319beb6ae6e:4603
ownerorigin https://www.youtube.com
googleads.g.doubleclick.net/pagead/id:1          Failed to load resource:
net::ERR_BLOCKED_BY_CLIENT
static.doubleclick.net/instream/ad_status.js:1          Failed to load
resource: net::ERR_BLOCKED_BY_CLIENT
VM10:949 TypeError: Cannot read properties of null (reading
'playerResponse')
The service worker navigation preload request was cancelled before
'preloadResponse' settled. If you intend to use 'preloadResponse', use
waitUntil() or respondWith() to wait for the promise to settle.
www.google.com/pagead/lvz?evtid=ADKXDuYmhDzekp9EXBSAJs6n0puI1_A8tKbTwEMpI68QTVqgWHmnPnk_BlRT5M3IhYxyMw1kkUT1A_c6nJQ_CL4To_Sn9YLTvA&req_ts=1658755139&pg=MainAppBootstrap%3AWatch&az=1&sigh=AN1MEdNEMIA0gY0WcdiHyIyQbu2jkrk41A:1
         Failed to load resource: net::ERR_BLOCKED_BY_CLIENT
www.google.com.tw/pagead/lvz?evtid=ADKXDuYmhDzekp9EXBSAJs6n0puI1_A8tKbTwEMpI68QTVqgWHmnPnk_BlRT5M3IhYxyMw1kkUT1A_c6nJQ_CL4To_Sn9YLTvA&req_ts=1658755139&pg=MainAppBootstrap%3AWatch&az=1&sigh=AN1MEdNEMIA0gY0WcdiHyIyQbu2jkrk41A:1
         Failed to load resource: net::ERR_BLOCKED_BY_CLIENT
live_chat_polymer.js:2791 LegacyDataMixin will be applied to all legacy
elements.
Set `_legacyUndefinedCheck: true` on element class to enable.
userscript.html?name=pttchatonyoutube.user.js&id=1a4522e4-1be2-41a6-a51b-7319beb6ae6e:12397
Uncaught (in promise) PTTonYT Script Stopped: Youtube should run in top
frame
userscript.html?name=pttchatonyoutube.user.js&id=1a4522e4-1be2-41a6-a51b-7319beb6ae6e:5526
Theme color check: website bgcolor is 'rgb(249, 249, 249)', WhiteThemeColor
is 'rgb(249, 249, 249)', whitetheme = true
userscript.html?name=pttchatonyoutube.user.js&id=1a4522e4-1be2-41a6-a51b-7319beb6ae6e:4559
PTTChatOnYT initialize finished at Youtube
userscript.html?name=pttchatonyoutube.user.js&id=1a4522e4-1be2-41a6-a51b-7319beb6ae6e:59
ReferenceError: GM_removeValueChangeListener is not defined
    at Cn.beforeDestroy
(userscript.html?name=pttchatonyoutube.user.js&id=1a4522e4-1be2-41a6-a51b-7319beb6ae6e:11633:9)
    at Be
(userscript.html?name=pttchatonyoutube.user.js&id=1a4522e4-1be2-41a6-a51b-7319beb6ae6e:59:11407)
    at Qt
(userscript.html?name=pttchatonyoutube.user.js&id=1a4522e4-1be2-41a6-a51b-7319beb6ae6e:59:25438)
    at e.$destroy
(userscript.html?name=pttchatonyoutube.user.js&id=1a4522e4-1be2-41a6-a51b-7319beb6ae6e:59:34898)
    at Proxy.<anonymous>
(userscript.html?name=pttchatonyoutube.user.js&id=1a4522e4-1be2-41a6-a51b-7319beb6ae6e:11603:17)
    at it (<anonymous>:14:1074)
    at t.<computed> (<anonymous>:38:422)
    at it (<anonymous>:14:1074)
    at <anonymous>:4:249
    at <anonymous>:9:314
    at it (<anonymous>:14:1074)
    at t (<anonymous>:15:364)
    at Object.message (<anonymous>:9:306)
    at Object.message (<anonymous>:10:111)
    at <anonymous>:66:379
    at M (<anonymous>:6:279)
Ve @
userscript.html?name=pttchatonyoutube.user.js&id=1a4522e4-1be2-41a6-a51b-7319beb6ae6e:59
userscript.html?name=pttchatonyoutube.user.js&id=1a4522e4-1be2-41a6-a51b-7319beb6ae6e:5938
Uncaught TypeError: Cannot read properties of undefined (reading '$refs')
    at a.scrollToChat
(userscript.html?name=pttchatonyoutube.user.js&id=1a4522e4-1be2-41a6-a51b-7319beb6ae6e:5938:29)
    at a.autoScrollCheck
(userscript.html?name=pttchatonyoutube.user.js&id=1a4522e4-1be2-41a6-a51b-7319beb6ae6e:5933:14)
    at Proxy.<anonymous>
(userscript.html?name=pttchatonyoutube.user.js&id=1a4522e4-1be2-41a6-a51b-7319beb6ae6e:5923:29)
    at it (<anonymous>:14:1074)
    at t.<computed> (<anonymous>:38:422)
    at it (<anonymous>:14:1074)
    at a (<anonymous>:3:446)
    at <anonymous>:4:111
    at <anonymous>:6:169
    at M (<anonymous>:6:188)
DevTools failed to load source map: Could not load content for
chrome-extension://dhdgffkkebhmkfjojejmpbldmpobfkfo/vue-virtual-scroller.min.js.map:
System error: net::ERR_BLOCKED_BY_CLIENT
DevTools failed to load source map: Could not load content for
https://www.youtube.com/s/desktop/ad3ffe7b/jsbin/custom-elements-es5-adapter.vflset/blaze-out/k8-opt/bin/third_party/javascript/custom_elements/fast-shim.js.sourcemap:
HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for
https://www.youtube.com/s/desktop/ad3ffe7b/jsbin/webcomponents-sd.vflset/blaze-out/k8-opt/bin/third_party/javascript/polymer/v2/webcomponentsjs/webcomponents-sd.js.sourcemap:
HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for
https://www.youtube.com/s/desktop/ad3ffe7b/jsbin/web-animations-next-lite.min.vflset/web-animations-next-lite.min.js.map:
HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for
https://www.youtube.com/global_styles_sass.css.map: HTTP error: status code
404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for
https://www.youtube.com/masthead_custom_styles_sass.css.map: HTTP error:
status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for
https://www.youtube.com/kevlar_global_styles_sass.css.map: HTTP error:
status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for
https://www.youtube.com/searchbox_sass.css.map: HTTP error: status code
404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for
https://www.youtube.com/masthead_shell_styles_sass.css.map: HTTP error:
status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for
https://www.youtube.com/yt-button-styles_custom_style.css.map: HTTP error:
status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for
https://www.youtube.com/yt-swatch-behavior_custom_style.css.map: HTTP
error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE

zoosewu ***@***.***> 於 2022年7月25日 週一 晚上7:08寫道：

**Comment by a26135768** [comment]
我也是跟上面的問題一樣
最近才這樣的，YT開不了但圖奇可以
油猴暴力猴都開不了，降級回3.04也沒辦法
然後開F12沒看到作者截圖的東西

**Comment by zoosewu** [comment]
我嘗試修正了可能的問題
但是我的環境沒有發生類似的錯誤 所以我沒辦法測試

有相同問題的人可以試試看3.0.6版 看問題有沒有解決
如果還是有一樣的問題的話還請再次打開F12幫我把錯誤訊息貼上來
感謝

**Comment by aces3732** [comment]
更新後一樣
[image: 1658844593966.jpg]
[image: 6a4910a9-c47b-4b2b-8dd5-50f5cfe81008.jpg]

The service worker navigation preload request was cancelled before
'preloadResponse' settled. If you intend to use 'preloadResponse', use
waitUntil() or respondWith() to wait for the promise to settle.
desktop_polymer.js:5964 LegacyDataMixin will be applied to all legacy
elements.
Set `_legacyUndefinedCheck: true` on element class to enable.
Youtube聊天室顯示PTT推文.user.js:4602 PTTChatOnYT Script started at Youtube, href:
https://www.youtube.com/watch?v=WntAEnscnII
Youtube聊天室顯示PTT推文.user.js:4603 ownerorigin https://www.youtube.com
Youtube聊天室顯示PTT推文.user.js:5526 Theme color check: website bgcolor is
'rgb(249, 249, 249)', WhiteThemeColor is 'rgb(249, 249, 249)', whitetheme =
true
Youtube聊天室顯示PTT推文.user.js:4559 PTTChatOnYT initialize finished at Youtube
The service worker navigation preload request was cancelled before
'preloadResponse' settled. If you intend to use 'preloadResponse', use
waitUntil() or respondWith() to wait for the promise to settle.
live_chat_polymer.js:2791 LegacyDataMixin will be applied to all legacy
elements.
Set `_legacyUndefinedCheck: true` on element class to enable.
Youtube聊天室顯示PTT推文.user.js:12397 PTTonYT Script Stopped: Youtube should run
in top frame
window.VMina7ijcempihen0c0 @ Youtube聊天室顯示PTT推文.user.js:12397
DevTools failed to load source map: Could not load content for
chrome-extension://jinjaccalgkegednnccohejagnlnfdag/vue-virtual-scroller.min.js.map:
System error: net::ERR_BLOCKED_BY_CLIENT
DevTools failed to load source map: Could not load content for
https://www.youtube.com/s/desktop/ad3ffe7b/jsbin/custom-elements-es5-adapter.vflset/blaze-out/k8-opt/bin/third_party/javascript/custom_elements/fast-shim.js.sourcemap:
HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for
https://www.youtube.com/s/desktop/ad3ffe7b/jsbin/webcomponents-sd.vflset/blaze-out/k8-opt/bin/third_party/javascript/polymer/v2/webcomponentsjs/webcomponents-sd.js.sourcemap:
HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for
https://www.youtube.com/s/desktop/ad3ffe7b/jsbin/web-animations-next-lite.min.vflset/web-animations-next-lite.min.js.map:
HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for
https://www.youtube.com/yt-swatch-behavior_custom_style.css.map: HTTP
error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for
https://www.youtube.com/global_styles_sass.css.map: HTTP error: status code
404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for
https://www.youtube.com/masthead_shell_styles_sass.css.map: HTTP error:
status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for
https://www.youtube.com/masthead_custom_styles_sass.css.map: HTTP error:
status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for
https://www.youtube.com/kevlar_global_styles_sass.css.map: HTTP error:
status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for
https://www.youtube.com/searchbox_sass.css.map: HTTP error: status code
404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for
https://www.youtube.com/yt-button-styles_custom_style.css.map: HTTP error:
status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
Youtube聊天室顯示PTT推文.user.js:5938 Uncaught TypeError: Cannot read properties
of undefined (reading '$refs')
    at a.scrollToChat (Youtube聊天室顯示PTT推文.user.js:5938:29)
    at a.autoScrollCheck (Youtube聊天室顯示PTT推文.user.js:5933:14)
    at Youtube聊天室顯示PTT推文.user.js:5923:29
scrollToChat @ Youtube聊天室顯示PTT推文.user.js:5938
autoScrollCheck @ Youtube聊天室顯示PTT推文.user.js:5933
(anonymous) @ Youtube聊天室顯示PTT推文.user.js:5923
setTimeout (async)
updateChat @ Youtube聊天室顯示PTT推文.user.js:5923
(anonymous) @ Youtube聊天室顯示PTT推文.user.js:6100
setInterval (async)
mounted @ Youtube聊天室顯示PTT推文.user.js:6099
Be @ Youtube聊天室顯示PTT推文.user.js:58
Qt @ Youtube聊天室顯示PTT推文.user.js:58
insert @ Youtube聊天室顯示PTT推文.user.js:58
k @ Youtube聊天室顯示PTT推文.user.js:58
(anonymous) @ Youtube聊天室顯示PTT推文.user.js:58
e._update @ Youtube聊天室顯示PTT推文.user.js:58
r @ Youtube聊天室顯示PTT推文.user.js:58
pn.get @ Youtube聊天室顯示PTT推文.user.js:58
pn @ Youtube聊天室顯示PTT推文.user.js:58
(anonymous) @ Youtube聊天室顯示PTT推文.user.js:58
Cn.$mount @ Youtube聊天室顯示PTT推文.user.js:58
Cn.$mount @ Youtube聊天室顯示PTT推文.user.js:58
t._init @ Youtube聊天室顯示PTT推文.user.js:58
Cn @ Youtube聊天室顯示PTT推文.user.js:58
InitChatApp @ Youtube聊天室顯示PTT推文.user.js:11520
InitApp @ Youtube聊天室顯示PTT推文.user.js:11504
CheckChatInstanced @ Youtube聊天室顯示PTT推文.user.js:11816

zoosewu ***@***.***> 於 2022年7月26日 週二 下午6:43寫道：

**Comment by zoosewu** [comment]
好 我會再看看

**Comment by a26135768** [comment]
我電腦重開機之後好像就修復了

**Comment by zoosewu** [comment]
目前還不清楚有沒有其他造成錯誤的原因
如果還有發生類似的問題希望能更詳細的描述上面所說的F12打開的資訊
以及如何進入Youtube的頁面的
輸入網址、從其他站點擊連結進入、從youtube首頁點影片進入...之類的

**Comment by GonzoHsu** [comment]
版本: 3.0.8

![螢幕擷取畫面 2023-02-03 195215](https://user-images.githubusercontent.com/122585887/216598053-91794067-fa61-4192-a70e-163eda553e52.png)

昨天開始突然看不到P  直連網址或從首頁點都一樣
