### ISSUE TITLE
[BUG] YT出現錯誤無法執行

### ISSUE THREAD

**Issue by GaruPeng** [zoosewu/PTTChatOnYoutube#133]
YT聊天室突然不會出現P按鈕，F12顯示如下:
----------------------------------------------------------

![bug](https://github.com/user-attachments/assets/191114fa-ad5b-4672-8a57-8ab66d8ba75b)

Youtube聊天室顯示PTT推文.user.js:2 
        
       Uncaught TypeError: Failed to set the 'innerHTML' property on 'Element': This document requires 'TrustedHTML' assignment.
    at Youtube聊天室顯示PTT推文.user.js:2:37815
    at Youtube聊天室顯示PTT推文.user.js:2:220
    at Youtube聊天室顯示PTT推文.user.js:2:225
    at Proxy.VM5e4xp41osbn (Youtube聊天室顯示PTT推文.user.js:12430:7)
    at Yt (injected-web.js:1:15586)
    at Youtube聊天室顯示PTT推文.user.js:1:20
    at async Gt (injected.js:1:8860)
    at async injected.js:1:14358

**Comment by kevin12314** [comment]
說說這個問題出現的原因，主要是Youtube改版，在 HTTP CSP 加入了require-trusted-types-for 'script' ，
該CSP主要是用來防禦XSS攻擊，會強制所有的HTML DOM 注入都必須使用TrustedHTML方式。
可參考以下連結：
https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Security-Policy/require-trusted-types-for

目前有支援require-trusted-types-for 'script' 的瀏覽器是Chrome、Edge、Opera等Chromium的瀏覽器，
Firefox和Safari都不支援，所以這兩個瀏覽器沒受到影響

Vue新版到目前為止都還未加入因應require-trusted-types-for 'script' CSP的修正，
所以要修正的話，可能就不能用Vue了，或是要去修改Vue.js源碼

**Comment by kevin12314** [comment]
~~現在Youtube好像又調整回來了，P按鈕又有顯示了~~
好像只是臨時的，今天又不見了

**Comment by kevin12314** [comment]
找到Workaround方式，再多裝下面的Script
[Youtube.TrustedHTML.-1.0.user.js](https://github.com/kevin12314/PTTChatOnYoutube/releases/download/v3.1.4-fix/Youtube.TrustedHTML.-1.0.user.js)

源碼：
``` javascript
// ==UserScript==
// @name         解除Youtube TrustedHTML 限制
// @namespace    http://tampermonkey.net/
// @version      1.0
// @description  解除Youtube TrustedHTML、TrustedScriptURL限制，讓Youtube聊天室顯示PTT推文Script可以執行
// @author       You
// @match        https://www.youtube.com/*
// @match        https://youtu.be/*
// @run-at       document-start
// @icon         https://www.google.com/s2/favicons?sz=64&domain=youtube.com
// @grant        none
// ==/UserScript==

(function() {
    if (window.trustedTypes && window.trustedTypes.createPolicy) {

        window.trustedTypes.createPolicy('default', {

            createHTML: string => string,

            createScriptURL: string => string,

            createScript: string => string,

        });

    }

    // Your code here...
})();
```
重新整理Youtube頁面，就能顯示了

![Image](https://github.com/user-attachments/assets/35621250-5c56-49d1-934a-506d13219741)
